# Generated by Django 5.0.2 on 2024-02-21 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('roles', models.ManyToManyField(related_name='preguntas', to='InformesMensuales.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento_identidad', models.CharField(blank=True, max_length=20, null=True)),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InformesMensuales.instrumento')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.rol')),
                ('sexo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InformesMensuales.sexo')),
                ('tipo_documento_identidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InformesMensuales.tipodocumentoidentidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.nivel')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InformeConsolidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_informe', models.CharField(max_length=20, unique=True)),
                ('consolidado', models.TextField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.usuario')),
            ],
        ),
    ]
