# Generated by Django 5.0.2 on 2024-02-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0002_usuario_groups_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
