# Generated by Django 5.0.2 on 2024-02-22 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0005_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
    ]
