# Generated by Django 5.0.2 on 2024-02-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0006_remove_usuario_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_documento_identidad',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InformesMensuales.tipodocumentoidentidad', unique=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='mes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.mes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuesta',
            name='mes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.mes'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UsuarioNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.nivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_asignados', to='InformesMensuales.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='UsuarioEscuela',
        ),
    ]
