# Generated by Django 5.0.2 on 2024-02-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0007_mes_alter_usuario_numero_documento_identidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InformesMensuales.tipodocumentoidentidad'),
        ),
    ]
