# Generated by Django 5.0.2 on 2024-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0008_alter_usuario_tipo_documento_identidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='niveles',
            field=models.ManyToManyField(related_name='ciclos', to='InformesMensuales.nivel'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='ciclos',
            field=models.ManyToManyField(related_name='escuelas', to='InformesMensuales.ciclo'),
        ),
    ]
