# Generated by Django 5.0.2 on 2024-02-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0010_remove_escuela_ciclos_remove_respuesta_escuela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciclo',
            name='niveles',
        ),
        migrations.RemoveField(
            model_name='usuarionivel',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='nivel',
            name='ciclo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='informeconsolidado',
            unique_together={('usuario', 'nivel', 'ciclo', 'escuela')},
        ),
    ]
