# Generated by Django 5.0.2 on 2024-03-04 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0011_remove_ciclo_niveles_remove_usuarionivel_ciclo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_documento_identidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='niveles',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usuarionivel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuarionivel',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='ciclo',
            name='escuela',
        ),
        migrations.RemoveField(
            model_name='nivel',
            name='ciclo',
        ),
        migrations.AddField(
            model_name='ciclo',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escuela',
            name='direccion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nivel',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciclo',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CicloNiveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaCiclos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesorEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_niveles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.cicloniveles')),
                ('escuela_ciclos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuelaciclos')),
                ('profesor_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.profesorescuela')),
            ],
        ),
        migrations.DeleteModel(
            name='InformeConsolidado',
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='TipoDocumentoIdentidad',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioNivel',
        ),
    ]
