# Generated by Django 5.0.2 on 2024-03-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0012_remove_usuario_instrumento_remove_respuesta_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.profesor')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.rol')),
            ],
        ),
        migrations.AddField(
            model_name='profesor',
            name='roles',
            field=models.ManyToManyField(through='InformesMensuales.ProfesorRoles', to='InformesMensuales.rol'),
        ),
    ]
