# Generated by Django 5.0.2 on 2024-03-04 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InformesMensuales', '0013_profesorroles_profesor_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=500)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.rol')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.ciclo')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.escuela')),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.mes')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.nivel')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.preguntas')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.profesor')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InformesMensuales.rol')),
            ],
        ),
    ]
